service: my-service

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  profile: ENTER_PROFILE_HERE

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello/world
          method: get
